version: '3.8'

services:
  jobscraper.web:
    image: jobscraper.web:latest
    build:
      context: .
      dockerfile: JobScraper.Web/Dockerfile
    ports:
      - "12986:8080"
    volumes:
      - data:/home/app/data

volumes:
  data:
