// <auto-generated />
using System;
using JobScraper.Web.Modules.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobScraper.Migrations
{
    [DbContext(typeof(JobsDbContext))]
    [Migration("20250119164334_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("JobScraper.Models.Company", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("IndeedUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("JjitUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ScrapedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("JobScraper.Models.JobOffer", b =>
                {
                    b.Property<string>("OfferUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgeInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplyUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("MyKeywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("OfferKeywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("Salary")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ScrapedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScreenShotPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("OfferUrl");

                    b.HasIndex("AgeInfo");

                    b.HasIndex("CompanyName");

                    b.HasIndex("Location");

                    b.HasIndex("Salary");

                    b.HasIndex("ScrapedAt");

                    b.ToTable("JobOffers", (string)null);
                });

            modelBuilder.Entity("JobScraper.Models.JobOffer", b =>
                {
                    b.HasOne("JobScraper.Models.Company", "Company")
                        .WithMany("JobOffers")
                        .HasForeignKey("CompanyName");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("JobScraper.Models.Company", b =>
                {
                    b.Navigation("JobOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
