// <auto-generated />
using System;
using JobScraper.Web.Modules.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobScraper.Migrations
{
    [DbContext(typeof(JobsDbContext))]
    [Migration("20260306173221_AiSummary_CvGenerationAfter")]
    partial class AiSummary_CvGenerationAfter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("JobScraper.Web.Common.Entities.AiSummaryConfig", b =>
                {
                    b.Property<string>("Owner")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AiSummaryEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CvContent")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CvGenerationEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultAiModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DefaultCvId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmartAiModel")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TestOfferContent")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserRequirements")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Owner");

                    b.HasIndex("DefaultCvId");

                    b.ToTable("AiSummaryConfigs", (string)null);
                });

            modelBuilder.Entity("JobScraper.Web.Common.Entities.Application", b =>
                {
                    b.Property<string>("Owner")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("OfferUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplyUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExpectedSalary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpectedSalaryCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SentCv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Owner", "OfferUrl");

                    b.HasIndex("AppliedAt");

                    b.HasIndex("ExpectedSalary");

                    b.HasIndex("OfferUrl");

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("JobScraper.Web.Common.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("JobScraper.Web.Common.Entities.Company", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(30000)
                        .HasColumnType("TEXT");

                    b.Property<string>("IndeedUrl")
                        .HasMaxLength(1023)
                        .HasColumnType("TEXT");

                    b.Property<string>("JjitUrl")
                        .HasMaxLength(1023)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoFluffJobsUrl")
                        .HasMaxLength(1023)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("JobScraper.Web.Common.Entities.CvEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Disclaimer")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ImageId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarkdownContent")
                        .IsRequired()
                        .HasMaxLength(30000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long?>("OriginCvId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Owner")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ImageId");

                    b.HasIndex("IsTemplate");

                    b.HasIndex("OriginCvId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Cvs", (string)null);
                });

            modelBuilder.Entity("JobScraper.Web.Common.Entities.ImageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasMaxLength(5242880)
                        .HasColumnType("BLOB");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Owner");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("CvImages", (string)null);
                });

            modelBuilder.Entity("JobScraper.Web.Common.Entities.JobOffer", b =>
                {
                    b.Property<string>("OfferUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsScrapeStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("ToScrape");

                    b.Property<string>("HtmlPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("OfferKeywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SalaryMaxMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SalaryMinMonth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScreenShotPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("OfferUrl");

                    b.HasIndex("CompanyName");

                    b.HasIndex("DetailsScrapeStatus");

                    b.HasIndex("Location");

                    b.HasIndex("SalaryCurrency");

                    b.HasIndex("SalaryMaxMonth");

                    b.HasIndex("SalaryMinMonth");

                    b.HasIndex("ScrapedAt");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("JobOffers", (string)null);
                });

            modelBuilder.Entity("JobScraper.Web.Common.Entities.ScraperConfig", b =>
                {
                    b.Property<string>("Owner")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AvoidKeywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrowserType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("MyKeywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SavePages")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SaveScreenshots")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScrapeCron")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowBrowserWhenScraping")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StarMyKeywords")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<float>("WaitForDetailsSeconds")
                        .HasColumnType("REAL");

                    b.Property<float>("WaitForListSeconds")
                        .HasColumnType("REAL");

                    b.Property<float>("WaitForScrollSeconds")
                        .HasColumnType("REAL");

                    b.HasKey("Owner");

                    b.ToTable("ScraperConfigs", (string)null);
                });

            modelBuilder.Entity("JobScraper.Web.Common.Entities.UserOffer", b =>
                {
                    b.Property<string>("Owner")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("OfferUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AiSummary")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("AiSummaryStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("None");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CvId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HideStatus")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("MyKeywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Owner", "OfferUrl");

                    b.HasIndex("CvId");

                    b.HasIndex("HideStatus");

                    b.HasIndex("OfferUrl");

                    b.ToTable("UserOffers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "6a427606-d71e-451e-9276-f363c43777f9",
                            ConcurrencyStamp = "019c70b8-19d0-715b-9595-2f4f60b20c02",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "6a427606-d71e-451e-9276-f363c43777f0",
                            ConcurrencyStamp = "019c70b8-19d0-715b-9595-2f4f60b20c03",
                            Name = "AiSummary",
                            NormalizedName = "AISUMMARY"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TickerQ.Utilities.Entities.CronTickerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Expression")
                        .HasColumnType("TEXT");

                    b.Property<string>("Function")
                        .HasColumnType("TEXT");

                    b.Property<string>("InitIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Request")
                        .HasColumnType("BLOB");

                    b.Property<int>("Retries")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("RetryIntervals")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Expression")
                        .HasDatabaseName("IX_CronTickers_Expression");

                    b.HasIndex("Function", "Expression")
                        .HasDatabaseName("IX_Function_Expression");

                    b.ToTable("CronTickers", "jobs");
                });

            modelBuilder.Entity("TickerQ.Utilities.Entities.CronTickerOccurrenceEntity<TickerQ.Utilities.Entities.CronTickerEntity>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CronTickerId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ElapsedTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LockHolder")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkippedReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CronTickerId")
                        .HasDatabaseName("IX_CronTickerOccurrence_CronTickerId");

                    b.HasIndex("ExecutionTime")
                        .HasDatabaseName("IX_CronTickerOccurrence_ExecutionTime");

                    b.HasIndex("CronTickerId", "ExecutionTime")
                        .IsUnique()
                        .HasDatabaseName("UQ_CronTickerId_ExecutionTime");

                    b.HasIndex("Status", "ExecutionTime")
                        .HasDatabaseName("IX_CronTickerOccurrence_Status_ExecutionTime");

                    b.ToTable("CronTickerOccurrences", "jobs");
                });

            modelBuilder.Entity("TickerQ.Utilities.Entities.TimeTickerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long>("ElapsedTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExecutionTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Function")
                        .HasColumnType("TEXT");

                    b.Property<string>("InitIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("LockHolder")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Request")
                        .HasColumnType("BLOB");

                    b.Property<int>("Retries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("RetryIntervals")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RunCondition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkippedReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionTime")
                        .HasDatabaseName("IX_TimeTicker_ExecutionTime");

                    b.HasIndex("ParentId");

                    b.HasIndex("Status", "ExecutionTime")
                        .HasDatabaseName("IX_TimeTicker_Status_ExecutionTime");

                    b.ToTable("TimeTickers", "jobs");
                });

            modelBuilder.Entity("JobScraper.Web.Common.Entities.AiSummaryConfig", b =>
                {
                    b.HasOne("JobScraper.Web.Common.Entities.CvEntity", "DefaultCv")
                        .WithMany()
                        .HasForeignKey("DefaultCvId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefaultCv");
                });

            modelBuilder.Entity("JobScraper.Web.Common.Entities.Application", b =>
                {
                    b.HasOne("JobScraper.Web.Common.Entities.UserOffer", "Offer")
                        .WithOne("Application")
                        .HasForeignKey("JobScraper.Web.Common.Entities.Application", "Owner", "OfferUrl")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("JobScraper.Web.Common.Entities.CvEntity", b =>
                {
                    b.HasOne("JobScraper.Web.Common.Entities.ImageEntity", "Image")
                        .WithMany("Cvs")
                        .HasForeignKey("ImageId");

                    b.HasOne("JobScraper.Web.Common.Entities.CvEntity", "OriginCv")
                        .WithMany("DerivedCvs")
                        .HasForeignKey("OriginCvId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsMany("JobScraper.Web.Common.Models.ChatItem", "ChatHistory", b1 =>
                        {
                            b1.Property<long>("CvEntityId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("AuthorName");

                            b1.Property<string>("Content");

                            b1.Property<string>("Role");

                            b1.HasKey("CvEntityId", "__synthesizedOrdinal");

                            b1.ToTable("Cvs");

                            b1
                                .ToJson("ChatHistory")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("CvEntityId");
                        });

                    b.OwnsOne("JobScraper.Web.Features.Cv.PdfGeneration.LayoutConfig", "LayoutConfig", b1 =>
                        {
                            b1.Property<long>("CvEntityId");

                            b1.Property<float>("DefaultFontSize");

                            b1.Property<string>("DisclaimerColor")
                                .IsRequired();

                            b1.Property<float>("DisclaimerFontSize");

                            b1.Property<string>("FontFamily")
                                .IsRequired();

                            b1.Property<float>("FooterPaddingBottom");

                            b1.Property<string>("H1FontColor")
                                .IsRequired();

                            b1.Property<float>("H1FontSize");

                            b1.Property<float>("H2FontSize");

                            b1.Property<float>("H3FontSize");

                            b1.Property<float>("H4FontSize");

                            b1.Property<float>("HeaderPaddingTop");

                            b1.Property<string>("HeaderUnderlineColor")
                                .IsRequired();

                            b1.Property<float>("HeaderUnderlineMaxLevel");

                            b1.Property<float>("HeaderUnderlinePaddingTop");

                            b1.Property<float>("HeaderUnderlineThickness");

                            b1.Property<string>("HeadingFontColorDefault")
                                .IsRequired();

                            b1.Property<float>("HeadingFontSizeDefault");

                            b1.Property<float>("HeadingPaddingBottom");

                            b1.Property<float>("HeadingPaddingTop");

                            b1.Property<string>("ImageBorderColor")
                                .IsRequired();

                            b1.Property<float>("ImageBorderRadius");

                            b1.Property<float>("ImageBorderThickness");

                            b1.Property<float>("ImageHeight");

                            b1.Property<float>("ImageMinSpaceFromText");

                            b1.Property<float>("LineHeight");

                            b1.Property<string>("ListBulletText")
                                .IsRequired();

                            b1.Property<float>("ListBulletWidth");

                            b1.Property<float>("ListPaddingLeft");

                            b1.Property<float>("MarginCm");

                            b1.Property<string>("PageBackgroundColor")
                                .IsRequired();

                            b1.Property<float>("ParagraphPaddingBottom");

                            b1.Property<int>("TextBlocksAlignedWithImage");

                            b1.Property<string>("ThematicBreakColor")
                                .IsRequired();

                            b1.Property<float>("ThematicBreakPaddingVertical");

                            b1.Property<float>("ThematicBreakThickness");

                            b1.Property<string>("UrlColor")
                                .IsRequired();

                            b1.HasKey("CvEntityId");

                            b1.ToTable("Cvs");

                            b1
                                .ToJson("LayoutConfig")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("CvEntityId");
                        });

                    b.Navigation("ChatHistory");

                    b.Navigation("Image");

                    b.Navigation("LayoutConfig")
                        .IsRequired();

                    b.Navigation("OriginCv");
                });

            modelBuilder.Entity("JobScraper.Web.Common.Entities.JobOffer", b =>
                {
                    b.HasOne("JobScraper.Web.Common.Entities.Company", "Company")
                        .WithMany("JobOffers")
                        .HasForeignKey("CompanyName");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("JobScraper.Web.Common.Entities.ScraperConfig", b =>
                {
                    b.OwnsMany("JobScraper.Web.Common.Entities.SourceConfig", "Sources", b1 =>
                        {
                            b1.Property<string>("ScraperConfigOwner");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<int>("DataOrigin");

                            b1.Property<bool>("Disabled");

                            b1.Property<string>("SearchUrl")
                                .IsRequired();

                            b1.HasKey("ScraperConfigOwner", "__synthesizedOrdinal");

                            b1.ToTable("ScraperConfigs");

                            b1
                                .ToJson("SourcesJson")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("ScraperConfigOwner");
                        });

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("JobScraper.Web.Common.Entities.UserOffer", b =>
                {
                    b.HasOne("JobScraper.Web.Common.Entities.CvEntity", "Cv")
                        .WithMany("Offers")
                        .HasForeignKey("CvId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JobScraper.Web.Common.Entities.JobOffer", "Details")
                        .WithMany("UserOffers")
                        .HasForeignKey("OfferUrl")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cv");

                    b.Navigation("Details");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("JobScraper.Web.Common.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("JobScraper.Web.Common.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobScraper.Web.Common.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("JobScraper.Web.Common.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TickerQ.Utilities.Entities.CronTickerOccurrenceEntity<TickerQ.Utilities.Entities.CronTickerEntity>", b =>
                {
                    b.HasOne("TickerQ.Utilities.Entities.CronTickerEntity", "CronTicker")
                        .WithMany()
                        .HasForeignKey("CronTickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CronTicker");
                });

            modelBuilder.Entity("TickerQ.Utilities.Entities.TimeTickerEntity", b =>
                {
                    b.HasOne("TickerQ.Utilities.Entities.TimeTickerEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("JobScraper.Web.Common.Entities.Company", b =>
                {
                    b.Navigation("JobOffers");
                });

            modelBuilder.Entity("JobScraper.Web.Common.Entities.CvEntity", b =>
                {
                    b.Navigation("DerivedCvs");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("JobScraper.Web.Common.Entities.ImageEntity", b =>
                {
                    b.Navigation("Cvs");
                });

            modelBuilder.Entity("JobScraper.Web.Common.Entities.JobOffer", b =>
                {
                    b.Navigation("UserOffers");
                });

            modelBuilder.Entity("JobScraper.Web.Common.Entities.UserOffer", b =>
                {
                    b.Navigation("Application");
                });

            modelBuilder.Entity("TickerQ.Utilities.Entities.TimeTickerEntity", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
